#
# Test for kernel
#
SUBDIRS	=  task thread ipc timer except fault deadlock sem mutex ioport \
	cap dvs

#
# Test for driver
#
SUBDIRS += kbd time zero fdd console ramdisk

#
# Test for library
#
SUBDIRS += errno malloc

include $(PREX_SRC)/make/Makefile.inc
