TARGET	= platform.o
TYPE	= OBJECT
OBJS	= \
	../i386/locore.o \
	../i386/trap.o \
	../i386/cpu.o \
	../i386/mmu.o \
	../i386/context.o \
	../i386/gdb_stub.o \
	intr.o clock.o diag.o serial.o
include $(PREX_SRC)/mk/sys.mk
