TARGET	= $(PREX_SRC)/user/lib/libc.a

OBJS	= \
	bcmp.o bcopy.o bzero.o ffs.o index.o memccpy.o memchr.o \
	memcmp.o memcpy.o memmove.o memset.o rindex.o strcasecmp.o strcat.o \
	strchr.o strcmp.o strcoll.o strcpy.o strncpy.o strncat.o strcspn.o \
	strftime.o strlen.o strmode.o strdup.o strncmp.o strerror.o \
	strpbrk.o strrchr.o strsep.o strspn.o strstr.o strtok.o strxfrm.o \
	swab.o strlcpy.o strlcat.o

include $(PREX_SRC)/mk/lib.mk
