TARGET	= dev.o
TYPE	= OBJECT
OBJS	= ../i386/start.o ../pc/dma.o ../pc/rtc.o ../pc/kbd.o ../pc/console.o \
	../pc/fdd.o ../pc/mouse.o ../i386/cpu.o ../pc/power.o ../i386/delay.o
include $(PREX_SRC)/make/dev.mk
