TARGET	= platform.o
TYPE	= OBJECT
OBJS	= \
	../i386/locore.o \
	../i386/trap.o \
	../i386/cpu.o \
	../i386/mmu.o \
	../i386/context.o \
	../i386/gdb_stub.o \
	../pc/intr.o \
	../pc/clock.o \
	../pc/diag.o \
	../pc/serial.o
include $(PREX_SRC)/make/sys.mk
