#
# Makefile to build Prex boot image
#
TARGET	= ../prexos
TYPE	= OS_IMAGE
LOADER	= $(PREX_SRC)/boot/bootldr
KERNEL	= $(PREX_SRC)/sys/prex

include $(PREX_SRC)/conf/make.conf
include $(PREX_SRC)/make/Makefile.inc
